Install/Uninstall now supports RPM, Debian, and Mac

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -12,16 +12,29 @@ SRC="${HOME}/src"
 
 . "${SRC}/${SRC_DIR}/VERSION"
 PKG_VER=${VERSION}
+PKG_REL=${RELEASE}
 
-DEB="${SRC}/${SRC_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}.deb"
+debian=
+have_apt=`type -p apt`
+have_dpkg=`type -p dpkg`
+have_rpm=`type -p rpm`
+have_yum=`type -p yum`
+[ -f /etc/os-release ] && . /etc/os-release
+[ "${ID_LIKE}" == "debian" ] && debian=1
+[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
 
-[ -f "${DEB}" ] || {
-    echo "$DEB not found."
-    for debs in ${SRC}/${SRC_DIR}/releases/*/${PKG_NAME}_*.deb
+SUF=deb
+[ "${debian}" ] || SUF=rpm
+
+PKG="${SRC}/${SRC_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
+
+[ -f "${PKG}" ] || {
+    echo "$PKG not found."
+    for pkgs in ${SRC}/${SRC_DIR}/releases/*/${PKG_NAME}_*.${SUF}
     do
-      [ "${debs}" == "${SRC}/${SRC_DIR}/releases/*/${PKG_NAME}_*.deb" ] || {
+      [ "${pkgs}" == "${SRC}/${SRC_DIR}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
         echo "Found existing packages:"
-        echo "${debs}"
+        echo "${pkgs}"
       }
     done
     echo "Exiting."
@@ -32,7 +45,33 @@ DEB="${SRC}/${SRC_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}.deb"
 # You should probably be running a more recent version of apt
 # On these early versions, install with the following:
 #
-# sudo dpkg -i "${DEB}"
+# sudo dpkg -i "${PKG}"
 # sudo apt-get install -f
 
-sudo apt install "${DEB}"
+echo "Installing ${PKG}"
+if [ "${debian}" ]
+then
+  if [ "${have_apt}" ]
+  then
+    sudo apt install "${PKG}"
+  else
+    if [ "${have_dpkg}" ]
+    then
+      sudo dpkg -i "${PKG}"
+    else
+      echo "Cannot locate either apt or dpkg to install. Skipping."
+    fi
+  fi
+else
+  if [ "${have_yum}" ]
+  then
+    sudo yum localinstall "${PKG}"
+  else
+    if [ "${have_rpm}" ]
+    then
+      sudo rpm -i "${PKG}"
+    else
+      echo "Cannot locate either yum or rpm to install. Skipping."
+    fi
+  fi
+fi
