Add Mac OS X installation and removal support, move postinstall and preremove out into etc

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -14,21 +14,26 @@ SRC="${HOME}/src"
 PKG_VER=${VERSION}
 PKG_REL=${RELEASE}
 
-debian=
-have_apt=`type -p apt`
-have_dpkg=`type -p dpkg`
-have_rpm=`type -p rpm`
-have_yum=`type -p yum`
-[ -f /etc/os-release ] && . /etc/os-release
-[ "${ID_LIKE}" == "debian" ] && debian=1
-[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
+plat=`uname -s`
+if [ "$plat" == "Darwin" ]
+then
+  ./macInstall
+else
+  debian=
+  have_apt=`type -p apt`
+  have_dpkg=`type -p dpkg`
+  have_rpm=`type -p rpm`
+  have_yum=`type -p yum`
+  [ -f /etc/os-release ] && . /etc/os-release
+  [ "${ID_LIKE}" == "debian" ] && debian=1
+  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
 
-SUF=deb
-[ "${debian}" ] || SUF=rpm
+  SUF=deb
+  [ "${debian}" ] || SUF=rpm
 
-PKG="${SRC}/${SRC_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
+  PKG="${SRC}/${SRC_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
 
-[ -f "${PKG}" ] || {
+  [ -f "${PKG}" ] || {
     echo "$PKG not found."
     for pkgs in ${SRC}/${SRC_DIR}/releases/*/${PKG_NAME}_*.${SUF}
     do
@@ -39,39 +44,40 @@ PKG="${SRC}/${SRC_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${S
     done
     echo "Exiting."
     exit 1
-}
+  }
 
-# Versions of apt prior to 1.1 do not support install by Debian filename
-# You should probably be running a more recent version of apt
-# On these early versions, install with the following:
-#
-# sudo dpkg -i "${PKG}"
-# sudo apt-get install -f
+  # Versions of apt prior to 1.1 do not support install by Debian filename
+  # You should probably be running a more recent version of apt
+  # On these early versions, install with the following:
+  #
+  # sudo dpkg -i "${PKG}"
+  # sudo apt-get install -f
 
-echo "Installing ${PKG}"
-if [ "${debian}" ]
-then
-  if [ "${have_apt}" ]
+  echo "Installing ${PKG}"
+  if [ "${debian}" ]
   then
-    sudo apt install "${PKG}"
-  else
-    if [ "${have_dpkg}" ]
+    if [ "${have_apt}" ]
     then
-      sudo dpkg -i "${PKG}"
+      sudo apt install "${PKG}"
     else
-      echo "Cannot locate either apt or dpkg to install. Skipping."
+      if [ "${have_dpkg}" ]
+      then
+        sudo dpkg -i "${PKG}"
+      else
+        echo "Cannot locate either apt or dpkg to install. Skipping."
+      fi
     fi
-  fi
-else
-  if [ "${have_yum}" ]
-  then
-    sudo yum localinstall "${PKG}"
   else
-    if [ "${have_rpm}" ]
+    if [ "${have_yum}" ]
     then
-      sudo rpm -i "${PKG}"
+      sudo yum localinstall "${PKG}"
     else
-      echo "Cannot locate either yum or rpm to install. Skipping."
+      if [ "${have_rpm}" ]
+      then
+        sudo rpm -i "${PKG}"
+      else
+        echo "Cannot locate either yum or rpm to install. Skipping."
+      fi
     fi
   fi
 fi
