Updated Utils/bin with scripts from my Mac Pro

diff --git a/Utils/bin/mvdown b/Utils/bin/mvdown
--- a/Utils/bin/mvdown
+++ b/Utils/bin/mvdown
@@ -1,51 +1,184 @@
 #!/bin/bash
 #
 
-[ "$1" ] || {
-    echo "Usage: ./mvdown model_name [-l]"
-    exit
+usage() {
+    printf "\nUsage: mvdown [-e] [-j] [-n] [-y] [-t top_dir] [-w working_dir] model_name"
+    printf "\nWhere:"
+    printf "\n\t-e indicates use Elite Babes folder"
+    printf "\n\t-j indicates use JP Erotica folder"
+    printf "\n\t-n indicates tell me what you would do without doing it"
+    printf "\n\t-t top_dir sets the top-level directory to use"
+    printf "\n\t-w working_dir sets the work directory under top_dir to use"
+    printf "\n\tmodel_name specifies a subdirectory containing the model photos to use"
+    printf "\n\tNo arguments indicates use the current working directory as destination"
+    printf "\n\nSettings with the given command-line options are as follows:"
+    printf "\n\ttop_dir=${TOP}"
+    printf "\n\tworking_dir=${WDIR}\n"
+    exit 1
 }
 
-TOP="/u/pictures/KindGirls"
-MODEL="$1"
-[ "$2" = "-l" ] && TOP="${HOME}/Pictures/Work.local/KindGirls"
-DEST="${TOP}/${MODEL}"
-DOWN="${HOME}/Pictures/DownThemAll"
+# Which system are we on?
+if [ -d /Volumes/Seagate_8TB/Pictures ]
+then
+    TOP="/Volumes/Seagate_8TB/Pictures"
+else
+    if [ -d /u/pictures ]
+    then
+        TOP="/u/pictures"
+    else
+        echo "Cannot determine top-level photo dir. Exiting."
+        exit 1
+    fi
+fi
+
+# Subfolder under $TOP where model folders are located
+WDIR="Work/KindGirls"
+
+EFLAG=
+JFLAG=
+YFLAG=
+TELL=
+USAGE=
+while getopts ejnt:w:yu flag; do
+    case $flag in
+        e)
+            WDIR="Work/Elite_Babes"
+            EFLAG=1
+            ;;
+        j)
+            WDIR="Work/JP_Erotica"
+            JFLAG=1
+            ;;
+        n)
+            TELL=1
+            ;;
+        t)
+            TOP="$OPTARG"
+            ;;
+        w)
+            WDIR="$OPTARG"
+            ;;
+        y)
+            YFLAG=1
+            ;;
+        u)
+            USAGE=1
+            ;;
+    esac
+done
+shift $(( OPTIND - 1 ))
+
+[ "$USAGE" ] && usage
+[ "$EFLAG" ] && [ "$JFLAG" ] && {
+    echo "The -e and -j options are mutually exclusive, use only one."
+    usage
+}
+
+[ -d ${TOP}/${WDIR} ] || {
+    echo "$TOP/$WDIR does not exist or is not a directory. Exiting."
+    usage
+}
+
+if [ "$1" ]
+then
+    MODEL=`echo $* | sed -e "s/ /_/g"`
+    DEST="${TOP}/${WDIR}/${MODEL}"
+else
+    DEST=`pwd`
+fi
+DOWN="${HOME}/Downloads/downthemall"
 
 [ -d ${DOWN} ] || {
     echo "$DOWN does not exist or is not a directory. Exiting."
     exit 1
 }
 
-[ -d ${DEST} ] || mkdir -p ${DEST}
+[ -d ${DEST} ] || {
+    if [ "${YFLAG}" ]
+    then
+        if [ "$TELL" ]
+        then
+            echo "mkdir -p ${DEST}"
+        else
+            mkdir -p "${DEST}"
+        fi
+    else
+      printf "\nModel directory $DEST does not exist or is not a directory.\n"
+      while true
+      do
+        read -p "Do you want to create the model directory $MODEL ? (y/n) " yn
+        case $yn in
+            [Yy]* ) if [ "$TELL" ]
+                    then
+                        echo "mkdir -p ${DEST}"
+                    else
+                        mkdir -p "${DEST}"
+                    fi
+                    break;;
+            [Nn]* ) printf "\nExiting.\n"; exit 1;;
+                * ) echo "Please answer yes or no.";;
+        esac
+      done
+    fi
+}
 
 cd "${DOWN}"
-rm -f extlink.png watch
+if [ "$TELL" ]
+then
+    echo "rm -f extlink.png watch"
+else
+    rm -f extlink.png watch
+fi
 moved=0
 for i in *.jpg
 do
     [ "$i" = "*.jpg" ] && {
         echo "No pics. Exiting."
         MOVNUM=`ls -1 "${DEST}" | wc -l`
-        [ ${MOVNUM} -gt 0 ] || rmdir "${DEST}"
+        [ ${MOVNUM} -gt 0 ] || {
+            if [ "$TELL" ]
+            then
+                echo "rmdir ${DEST}"
+            else
+                rmdir "${DEST}"
+            fi
+        }
         exit 1
     }
     [ -r "${DEST}/$i" ] && {
         echo "${DEST}/$i already exists. Skipping."
-        [ -d __Skipped__ ] || mkdir __Skipped__
-        mv "$i" __Skipped__
+        [ -d __Skipped__ ] || {
+            if [ "$TELL" ]
+            then
+                echo "mkdir __Skipped__"
+            else
+                mkdir __Skipped__
+            fi
+        }
+        if [ "$TELL" ]
+        then
+            echo "mv $i __Skipped__"
+        else
+            mv "$i" __Skipped__
+        fi
         continue
     }
-    # mv "$i" "${DEST}"
-    cp "$i" "${DEST}" && rm -f "$i"
+    if [ "$TELL" ]
+    then
+        echo "cp $i ${DEST} && rm -f $i"
+    else
+        cp "$i" "${DEST}" && rm -f "$i"
+    fi
     moved=`expr $moved + 1`
 done
 echo "Moved $moved pics to ${DEST}"
 
-NUM=`ls -1 | grep -v __Skipped__ | wc -l`
+[ "$TELL" ] || {
+    NUM=`ls -1 | grep -v __Skipped__ | wc -l`
 
-[ ${NUM} -gt 1 ] && {
-    echo ""
-    echo "Additional pics: "
-    ls -1 | grep -v mvall | grep -v __Skipped__
+    [ ${NUM} -gt 1 ] && {
+        echo ""
+        echo "Additional pics: "
+        ls -1 | grep -v mvall | grep -v __Skipped__
+    }
 }
diff --git a/Utils/bin/slideshow b/Utils/bin/slideshow
--- a/Utils/bin/slideshow
+++ b/Utils/bin/slideshow
@@ -1,63 +1,273 @@
 #!/bin/bash
+#
+## @file Wallpapers/backgrounds.sh
+## @brief Set background desktop wallpapers or display slideshow
+## @author Ronald Joe Record (rr at ronrecord dot com)
+## @copyright Copyright (c) 2017, Ronald Joe Record, all rights reserved.
+## @date Written 17-Sep-2017
+## @version 2.0.1
+##
+## NOTES:
+##
+## Link the file "backgrounds" to "slides" and/or "slideshow" to enable
+## and turn on automatic slideshow presentation when invoked as such.
+##
+## I found I needed to give iTerm2 system privileges in
+## System Preferences -> Security & Privacy -> Privacy
+## Adding it to the list of applications given Accessibility and Full Disk Access
+## privileges. On another system I needed to add "System Events" rather than "iTerm 2"
+## to Accessibility so ymmv - apparently this is a result of strengthened privacy
+## protections in Apple's Mojave release.
+##
+## You may wish to add the "Slideshow" icon to the Preview toolbar for ease of use
+##
 
-top=/u/pictures
-out=$HOME/.config/variety/Favorites
+# Root directory of your subfolders of image files to use as backgrounds/slideshows
+LIN_TOP=/u/pictures
+MAC_TOP="/Volumes/Seagate_8TB/Pictures/Work"
+NFS_TOP=/u/pictures/Work
+#
+# Location of folder to copy selected images to
+MAC_OUT=$HOME/Pictures/Backgrounds
+LIN_OUT=/usr/local/share/backgrounds
+#
+# Folders to search for model name or other subfolder of images to use
+# These are located under $TOP, defined below
+# Order is important, first in list coming first in search
+# If you want to combine images from several folders use the "-s all" option
+#
+SUBS="Wallhaven Wallhaven/Models Wallhaven/Photographers X-Art Elite_Babes JP_Erotica \
+      Met-Art KindGirls Wallbase"
+
 bak=/tmp/pic$$
+maxlinks=2048
+add=
+all=
+osa=
+show=
+subdir=
+foundirs=
+name=`basename $0`
+plat=`uname -s`
 
-[ -d $out ] || {
-    echo "$out does not exist or is not a directory. Exiting."
-    exit 1
+usage() {
+  printf "\nUsage: $name [-u] [-a] [-l] [-S] [-n numpics] [-s subdir] directory"
+  printf "\nWhere\t-a indicates add to existing background/slide pics"
+  printf "\n\t-l lists currently installed background/slide pics"
+  printf "\n\t-n <numpics> sets maximum number of pics to be copied (default ${maxlinks})"
+  printf "\n\t-s <subdir> searches in $TOP/<subdir> for specified folder"
+  printf "\n\t-S indicates run a slideshow of pics\n\n"
+  exit 1
 }
-cd $out
-[ "$1" ] && {
-  mkdir $bak
-  touch $bak/foo
-  for i in *
-  do
-    [ "$i" == "*" ] && continue
-    mv $i $bak
-  done
 
-  [ -d $top/$1 ] || {
-    for subdir in Elite_Babes JP_Erotica KindGirls Wallbase Wallhaven X-Art
+# Turn on slideshow capability if invoked as "slides" or "slideshow"
+[ "$name" == "slides" ] && show=1
+[ "$name" == "slideshow" ] && show=1
+
+# Try to figure out which system we are on
+if [ "$plat" == "Linux" ]
+then
+    TOP="$LIN_TOP"
+    OUT="$LIN_OUT"
+    SLIDE_APP="Variety Slideshow"
+else
+    if [ "$plat" == "Darwin" ]
+    then
+        TOP="$MAC_TOP"
+        OUT="$MAC_OUT"
+        SLIDE_APP="AppleScript"
+    else
+        echo "Unable to detect a supported platform: ${plat}. Exiting."
+        exit 1
+    fi
+fi
+[ -d "$TOP" ] || {
+    TOP="$NFS_TOP"
+    [ -d "$TOP" ] || {
+        echo "Cannot locate Work directory for pics. Exiting."
+        exit 1
+    }
+}
+  
+while getopts n:s:alSu flag; do
+    case $flag in
+        a)
+            add=1
+            ;;
+        l)
+#           ls --color=auto -l $OUT | awk ' { print $NF } '
+            ls -l $OUT | awk ' { print $NF } '
+            exit 0
+            ;;
+        n)
+            maxlinks="$OPTARG"
+            ;;
+        s)
+            case "$OPTARG" in
+              all) all=1
+                ;;
+              elite) subdir="Elite_Babes"
+                ;;
+              jp) subdir="JP_Erotica"
+                ;;
+              kind) subdir="KindGirls"
+                ;;
+              whvn) subdir="Wallhaven/Models"
+                ;;
+              xart) subdir="X-Art"
+                ;;
+              *) subdir="$OPTARG"
+                ;;
+            esac
+            ;;
+        S)
+            show=1
+            ;;
+        u)
+            usage
+            ;;
+    esac
+done
+shift $(( OPTIND - 1 ))
+
+[ "$show" ] && {
+    if [ "$plat" == "Darwin" ]
+    then
+        inst=`type -p osascript`
+        [ "$inst" ] && osa=1
+    else
+        inst=`type -p variety-slideshow`
+        [ "$inst" ] && var=1
+    fi
+    [ "$inst" ] || {
+        echo "$SLIDE_APP is not supported on this platform."
+        echo "Unable to automate the slideshow feature."
+    }
+}
+
+[ -d $OUT ] || {
+    sudo mkdir $OUT
+    user=`id -u -n`
+    sudo chown $user $OUT
+}
+
+cd $OUT
+
+[ "$1" ] && {
+  [ "$add" ] || {
+    mkdir $bak
+    touch $bak/foo
+    for i in *
     do
-      [ -d $top/$subdir/$1 ] && {
-        top=$top/$subdir
-        break
-      }
+      [ "$i" == "*" ] && continue
+      mv $i $bak
     done
   }
-  [ -d $top/$1 ] || {
-    echo "Cannot locate $top/$1 - exiting."
+
+  bdir="$1"
+  if [ "$bdir" == "favs" ]
+  then
+    TOP="$HOME/Pictures"
+    bdir="Favs"
+    foundirs=$TOP
+  else
+    if [ "$subdir" ]
+    then
+      [ -d "$TOP/$subdir/$bdir" ] || {
+        echo "Cannot locate $TOP/$subdir/$bdir - exiting."
+        exit 1
+      }
+      TOP=$TOP/$subdir
+      foundirs=$TOP
+    else
+      [ -d $TOP/$bdir ] || {
+       for subdir in Wallhaven Wallhaven/Models Wallhaven/Photographers X-Art Elite_Babes JP_Erotica Met-Art KindGirls Wallbase
+       do
+         [ -d $TOP/$subdir/$bdir ] && {
+           sub=$TOP/$subdir
+           if [ "$all" ]
+           then
+             foundirs="$foundirs $sub"
+           else
+             foundirs=$sub
+             break
+           fi
+         }
+       done
+       TOP=$sub
+      }
+    fi
+  fi
+  [ -d "$TOP/$bdir" ] || {
+    echo "Cannot locate $TOP/$bdir - exiting."
     exit 1
   }
 
-  for dir in $*
+  numlinks=0
+  for dir in $foundirs
   do
-    [ -d $top/$dir ] && {
-        for pic in $top/$dir/*
+    for pic in $dir/$bdir/*
+    do
+      [ "$pic" == "$dir/$bdir/*" ] && continue
+      [ "$pic" == "$dir/$bdir/downloaded.txt" ] && continue
+      [ "$pic" == "$dir/$bdir/Description.txt" ] && continue
+      if [ -d "$pic" ]
+      then
+        for subpic in $pic/*
         do
-          [ "$pic" == "$top/$dir/*" ] && continue
-          [ "$pic" == "$top/$dir/downloaded.txt" ] && continue
-          ln -s $pic .
+          [ "$subpic" == "$pic/*" ] && continue
+          [ "$subpic" == "$pic/downloaded.txt" ] && continue
+          [ "$subpic" == "$pic/Description.txt" ] && continue
+          [ -d "$subpic" ] && continue
+#       bnam=`basename $subpic`
+#       [ -L $bnam ] && continue
+#       ln -s $subpic .
+          cp $subpic .
+          numlinks=`expr $numlinks + 1`
+          [ $numlinks -ge $maxlinks ] && break 2
         done
-    }
+      else
+#     bnam=`basename $pic`
+#     [ -L $bnam ] && continue
+#     ln -s $pic .
+        cp $pic .
+        numlinks=`expr $numlinks + 1`
+      fi
+      [ $numlinks -ge $maxlinks ] && break 2
+    done
   done
+
   for j in *
   do
     [ "$j" == "*" ] && {
-      mv $bak/* .
-      rm -f foo
+      [ "$add" ] || {
+        mv $bak/* .
+        rm -f foo
+      }
       continue
     }
     file -L $j | grep ASCII > /dev/null && rm -f $j
   done
-  rm -rf $bak
+  [ "$add" ] || rm -rf $bak
 }
-numfavs=`ls -1 $HOME/.config/variety/Favorites | wc -l`
-if [ $numfavs -gt 0 ]
-then
-    variety-slideshow $HOME/.config/variety/Favorites 2> /dev/null
-else
-    variety-slideshow /usr/local/share/backgrounds 2> /dev/null
-fi
+
+[ "$show" ] && {
+    if [ "$plat" == "Darwin" ]
+    then
+        open -a Preview "$OUT"/*
+        # ----------------------
+        # Applescript below here
+        # ----------------------
+        [ "$osa" ] && {
+            osascript <<EOF
+            delay 5
+            tell application "System Events"
+                keystroke "F" using {shift down, command down}
+            end tell
+EOF
+        }
+    else
+#           variety-slideshow $HOME/.config/variety/Favorites 2> /dev/null
+            variety-slideshow "$OUT" 2> /dev/null
+    fi
+}
