Last pass at filtering commands for linking into /usr/local/bin, moving and deleting scripts

diff --git a/Utils/bin/puml b/Utils/bin/puml
--- a/Utils/bin/puml
+++ b/Utils/bin/puml
@@ -2,6 +2,15 @@
 
 DIAG_DIR=${HOME}/Diagrams/src
 
+inst=`type -p plantuml`
+[ "${inst}" ] || {
+    echo "Cannot locate required application 'plantuml'."
+    echo "The plantuml application can be downloaded at"
+    echo "https://plantuml.com/download"
+    echo "Exiting."
+    exit 1
+}
+
 [ -d ${DIAG_DIR} ] || mkdir -p ${DIAG_DIR}
 [ -d ${DIAG_DIR}/../PNG ] || mkdir -p ${DIAG_DIR}/../PNG
 cd ${DIAG_DIR}
diff --git a/Utils/bin/variety-fractals b/Utils/bin/variety-fractals
--- a/Utils/bin/variety-fractals
+++ b/Utils/bin/variety-fractals
@@ -1,9 +1,17 @@
 #!/bin/bash
 
-/usr/bin/variety --quit
+inst=`type -p variety`
+[ "${inst}" ] || {
+    echo "The variety application cannot be located in your execution PATH."
+    echo "To install variety, see https://peterlevi.com/variety/how-to-install/"
+    echo "Exiting."
+    exit 1
+}
+
+variety --quit
 
 sleep 2
-echo "/home/ronnie/.config/variety-fractals/" > ~/.variety-profile
+echo "${HOME}/.config/variety-fractals/" > ~/.variety-profile
 
-/usr/bin/variety --profile \
-    /home/ronnie/.config/variety-fractals/ > /dev/null 2>&1 &
+variety --profile \
+    ${HOME}/.config/variety-fractals/ > /dev/null 2>&1 &
diff --git a/Utils/bin/variety-next b/Utils/bin/variety-next
--- a/Utils/bin/variety-next
+++ b/Utils/bin/variety-next
@@ -1,6 +1,14 @@
 #!/bin/bash
 
-PROF="/home/ronnie/.config/variety"
+inst=`type -p variety`
+[ "${inst}" ] || {
+    echo "The variety application cannot be located in your execution PATH."
+    echo "To install variety, see https://peterlevi.com/variety/how-to-install/"
+    echo "Exiting."
+    exit 1
+}
+
+PROF="${HOME}/.config/variety"
 [ -f ~/.variety-profile ] && PROF=`cat ~/.variety-profile`
 
-/usr/bin/variety --profile "$PROF" --next > /dev/null 2>&1 &
+variety --profile "$PROF" --next > /dev/null 2>&1 &
diff --git a/Utils/bin/variety-set b/Utils/bin/variety-set
--- a/Utils/bin/variety-set
+++ b/Utils/bin/variety-set
@@ -1,7 +1,15 @@
 #!/bin/bash
 
-PIC=/home/ronnie/Pictures/wallpaper-999544.jpg
-PROF="/home/ronnie/.config/variety"
+inst=`type -p variety`
+[ "${inst}" ] || {
+    echo "The variety application cannot be located in your execution PATH."
+    echo "To install variety, see https://peterlevi.com/variety/how-to-install/"
+    echo "Exiting."
+    exit 1
+}
+
+PIC=${HOME}/Pictures/wallpaper-999544.jpg
+PROF="${HOME}/.config/variety"
 
 [ "$1" ] && {
     [ -f "$1" ] && {
@@ -11,4 +19,4 @@ PROF="/home/ronnie/.config/variety"
 
 [ -f ~/.variety-profile ] && PROF=`cat ~/.variety-profile`
 
-/usr/bin/variety --profile "$PROF" --set $PIC > /dev/null 2>&1 &
+variety --profile "$PROF" --set $PIC > /dev/null 2>&1 &
