Updated gdrive utility scripts

diff --git a/gdrive/bin/gdrm b/gdrive/bin/gdrm
--- a/gdrive/bin/gdrm
+++ b/gdrive/bin/gdrm
@@ -1,13 +1,54 @@
 #!/bin/bash
 #
+GHOM=${HOME}/.gdrive
 GDOPTS="--no-header --absolute --max 100 --name-width 0"
+
+[ -f ${GHOM}/gdhome ] || {
+    HERE=`pwd`
+    while true
+    do
+        read -p "Initializing gdrive home to ${HERE}. Ok ? ('Y'/'N'): " yn
+        case $yn in
+            [Yy]*)
+                [ -d ${GHOM} ] || mkdir -p ${GHOM}
+                echo "GDHOME=${HERE}" > ${GHOM}/gdhome
+                break
+                ;;
+            [Nn]*)
+                read -p "Enter your gdrive home: " gdhome
+                case ${gdhome} in
+                    *)
+                        echo "GDHOME=${gdhome}" > ${GHOM}/gdhome
+                        ;;
+                esac
+                break
+                ;;
+            * )
+                echo "Please answer yes or no."
+                ;;
+        esac
+    done
+}
+
+. ${GHOM}/gdhome
+[ -d ${GDHOME} ] || {
+    echo "Cannot locate gdrive home ${GDHOME}"
+    echo "Edit ${GHOM}/gdhome and set your local gdrive home"
+    exit 1
+}
+cd ${GDHOME}
 
 TELL=
 splitpath=1
 recursive=
 
 usage() {
-  printf "\nUsage: gdrm [-n] [-r] [-s] [-u] path/to/fileorfolder [file2 ...]\n"
+  printf "\nUsage: gdrm [-n] [-r] [-s] [-u] path/to/fileorfolder [file2 ...]"
+  printf "\nWhere:\n\t-n indicates tell me what you would do but don't do it"
+  printf "\n\t-r indicates remove directory and its contents recursively"
+  printf "\n\t-s indicates do not split path to identify name"
+  printf "\n\t\t(useful when there is a slash in the filename)"
+  printf "\n\t-u displays this usage message\n"
   exit 1
 }
 
@@ -31,7 +72,7 @@ shift $(( OPTIND - 1 ))
 
 [ "$1" ] || {
   echo "rmfile requires at least one argument specifying folder or file to remove"
-  exit 1
+  usage
 }
 
 for file in $*
@@ -39,16 +80,21 @@ do
   base=${file}
   dir=
   parentid=
-  parentquery=
+  [ -f .folderid ] && parentid=`cat .folderid`
   [ "${splitpath}" ] && {
     echo ${file} | grep '/' > /dev/null && {
       base=`basename ${file}`
       dir=`dirname ${file}`
       [ -f ${dir}/.folderid ] && {
         parentid=`cat ${dir}/.folderid`
-        parentquery="and parents in '${parentid}'"
       }
     }
+  }
+  [ "${parentid}" ] || {
+    echo "Cannot locate parent id"
+    echo "Run 'getfileids' to populate folders with folder ids"
+    echo "Exiting without sync"
+    exit 1
   }
 
   while read match
@@ -56,12 +102,23 @@ do
     name=`echo ${match} | awk ' { print $2 } '`
     [ "${name}" == "${file}" ] && {
       fid=`echo ${match} | awk ' { print $1 } '`
+      typ=`echo ${match} | awk ' { print $3 } '`
+      [ "${typ}" == "dir" ] && {
+        [ "${recursive}" ] || {
+          echo "${file} is a directory but no -r flag was provided."
+          echo "To remove a directory, use 'gdrm -r ...' to recursively delete"
+          echo "the directory and its contents."
+          echo "Skipping removal of ${file}."
+          continue
+        }
+      }
       if [ "${TELL}" ]
       then
-        echo "Would remove ${file} with id=${fid}"
+        echo "Would remove ${file} with id=${fid} with command:"
+        echo "gdrive delete ${recursive} ${fid}"
       else
         gdrive delete ${recursive} ${fid}
       fi
     }
-  done <<< `gdrive list ${GDOPTS} --query " name = '${base}' ${parentquery}"`
+  done <<< `gdrive list ${GDOPTS} --query " name = '${base}' and parents in '${parentid}'"`
 done
diff --git a/gdrive/bin/getfileids b/gdrive/bin/getfileids
--- a/gdrive/bin/getfileids
+++ b/gdrive/bin/getfileids
@@ -35,21 +35,30 @@ GHOM=${HOME}/.gdrive
     echo "Edit ${GHOM}/gdhome and set your local gdrive home"
     exit 1
 }
-TOP=${GDHOME}
 cd ${GDHOME}
-ID_DIR="${TOP}/drive_ids"
-BU_DIR="${TOP}/Bak/drive_ids"
+ID_DIR="${GDHOME}/drive_ids"
+BU_DIR="${GDHOME}/Bak/drive_ids"
 FIDLIST="${ID_DIR}/mirror_file_ids.txt"
 DIRLIST="${ID_DIR}/mirror_folder_ids.txt"
 FIDBULIST="${BU_DIR}/mirror_file_ids.txt"
 DIRBULIST="${BU_DIR}/mirror_folder_ids.txt"
 GDOPTS="--no-header --absolute --max 50 --name-width 0"
 
-# MagicMirror folder ID
-MMID='1ZAvsixgtwH14ejxEUxpkZnRPYFFInBJe'
+# Get top folder ID by creating a directory, getting its parent id, then remove it
+tmpfolder="__tmpfolder__$$"
+TMPFID=`gdrive mkdir ${tmpfolder} | awk ' { print $2 } '`
+GDID=`gdrive info ${TMPFID} | grep Parents: | awk ' { print $2 } '`
+echo "Retrieved top level folder ID = ${GDID}"
+gdrive delete --recursive ${TMPFID}
+[ "${GDID}" ] || {
+  echo "Could not retrieve top-level drive ID"
+  echo "Using previously created setting for top-level ID"
+  # Replace this ID with the ID of the top level of your Google Drive
+  # that you wish to use with the gdrive command line utility
+  GDID='0AHIaKKQ-Wu1RUk9PVA'
+}
 
-[ -d ${TOP} ] || mkdir -p ${TOP}
-[ -d ${TOP}/MagicMirror ] || mkdir -p ${TOP}/MagicMirror
+[ -d ${GDHOME}/MagicMirror ] || mkdir -p ${GDHOME}/MagicMirror
 [ -d ${ID_DIR} ] || mkdir -p ${ID_DIR}
 [ -d ${BU_DIR} ] || mkdir -p ${BU_DIR}
 [ -f ${FIDLIST} ] && mv ${FIDLIST} ${FIDBULIST}$$
@@ -57,9 +66,7 @@ touch ${FIDLIST}
 [ -f ${DIRLIST} ] && mv ${DIRLIST} ${DIRBULIST}$$
 touch ${DIRLIST}
 
-cd ${TOP}
-echo "MagicMirror=${MMID}" >> ${DIRLIST}
-echo "${MMID}" > MagicMirror/.folderid
+echo "${GDID}" > .folderid
 
 getids() {
   while read entry
@@ -81,9 +88,9 @@ getids() {
 }
 
 subdirIDs=
-# Start at MagicMirror folder
+# Start at top folder
 # Recursion would be nice
-getids ${MMID}
+getids ${GDID}
 [ "${subdirIDs}" ] && {
   for folderID in ${subdirIDs}
   do
@@ -99,6 +106,13 @@ getids ${MMID}
           do
             subdirIDs=
             getids ${subSubFolderID}
+            [ "${subdirIDs}" ] && {
+              for finalFolderID in ${subdirIDs}
+              do
+                subdirIDs=
+                getids ${finalFolderID}
+              done
+            }
           done
         }
       done
diff --git a/gdrive/bin/sync2drive b/gdrive/bin/sync2drive
--- a/gdrive/bin/sync2drive
+++ b/gdrive/bin/sync2drive
@@ -37,41 +37,111 @@ GHOM=${HOME}/.gdrive
 }
 cd ${GDHOME}
 
-FOLDER="$1"
-[ "${FOLDER}" ] || {
+TELL=
+splitpath=1
+
+usage() {
+  printf "\nUsage: sync2drive [-m maxfiles] [-n] [-s] [-u] folder | path/to/folder"
+  printf "\nWhere:\n\t-m 'maxfiles' specifies maximum number of file ids to return"
+  printf "\n\t\t(default: 100)"
+  printf "\n\t-n indicates tell me what you would do but don't do it"
+  printf "\n\t-s indicates do not split path to identify name"
+  printf "\n\t\t(useful when there is a slash in the folder name)"
+  printf "\n\t-u displays this usage message\n"
+  exit 1
+}
+
+maxfiles=100
+while getopts "m:nsu" flag; do
+    case $flag in
+        m)
+            maxfiles=${OPTARG}
+            ;;
+        n)
+            TELL=1
+            ;;
+        s)
+            splitpath=
+            ;;
+        u)
+            usage
+            ;;
+    esac
+done
+shift $(( OPTIND - 1 ))
+
+GDOPTS="--no-header --absolute --max ${maxfiles} --name-width 0"
+
+folder="$1"
+[ "${folder}" ] || {
     echo "sync2drive requires a folder name as argument"
-    echo "Exiting"
-    exit 1
+    usage
 }
-[ -d "${FOLDER}" ] || {
+[ -d "${folder}" ] || {
     echo "sync2drive requires an existing local folder"
-    echo "No folder ${FOLDER} found. Exiting"
-    exit 1
+    echo "No folder ${folder} found. Exiting"
+    usage
 }
 
-# Does this folder already exist?
-
-useparent=
-echo "${FOLDER}" | grep '/' > /dev/null && {
+base=${folder}
+pdir=
+parentid=
+[ -f .folderid ] && parentid=`cat .folderid`
+echo "${folder}" | grep '/' > /dev/null && {
     # Get the parent folder ID
-    pdir=`dirname ${FOLDER}`
+    pdir=`dirname ${folder}`
     [ -f ${pdir}/.folderid ] || {
         echo "Cannot locate ${pdir}/.folderid"
         echo "Run 'getfileids' to populate folders with folder ids"
         echo "Exiting without sync"
         exit 1
     }
-    useparent=1
-    PARENTID=`cat ${pdir}/.folderid`
+    base=`basename ${folder}`
+    parentid=`cat ${pdir}/.folderid`
+}
+[ "${parentid}" ] || {
+    echo "Could not establish parent id."
+    echo "Run 'getfileids' to populate folders with folder ids"
+    echo "Exiting without sync"
+    exit 1
 }
 
-# Create directory on drive
-if [ "${useparent}" ]
-then
-    FID=`gdrive mkdir --parent ${PARENTID} ${FOLDER} | awk ' { print $2 } '`
-else
-    FID=`gdrive mkdir ${FOLDER} | awk ' { print $2 } '`
-fi
+# Does this folder already exist?
+exists=
+while read match
+do
+    name=`echo ${match} | awk ' { print $2 } '`
+    [ "${name}" == "${folder}" ] && {
+      exists=`echo ${match} | awk ' { print $1 } '`
+    }
+done <<< `gdrive list ${GDOPTS} --query " name = '${base}' and parents in '${parentid}'"`
+
+[ "${exists}" ] || {
+  [ "${TELL}" ] && echo "Would create new folder ${folder} in Google Drive"
+  # Create directory on drive
+  if [ "${parentid}" ]
+  then
+      if [ "${TELL}" ]
+      then
+        echo "gdrive mkdir --parent ${parentid} ${folder} | awk ' { print FID } '"
+      else
+        FID=`gdrive mkdir --parent ${parentid} ${folder} | awk ' { print $2 } '`
+      fi
+  else
+      if [ "${TELL}" ]
+      then
+        echo "gdrive mkdir ${folder} | awk ' { print FID } '"
+      else
+        FID=`gdrive mkdir ${folder} | awk ' { print $2 } '`
+      fi
+  fi
+}
 
 # Sync to drive
-gdrive sync upload ${FOLDER} ${FID}
+if [ "${TELL}" ]
+then
+    echo "Would sync new folder ${folder} in Google Drive"
+    echo "gdrive sync upload ${folder} FID"
+else
+    gdrive sync upload ${folder} ${FID}
+fi
